package reinforcementLabs;

public class Reinforcement {
	public static void main(String[] args) {

	}

	/**
	 * 1 Give the next five pseudorandom numbers generated by the process described
	 * on page 113, with a = 12, b = 5, and n = 100, and 92 as the seed for cur.
	 * 
	 */
	public static int giveSeed(int a, int b, int n, int seed) {
		return (a * seed + b) % n;

	}
}
